### ISSUE TITLE
create base image version for aws that targets k8s 1.17

### ISSUE THREAD

**Issue by geoff-elastisys** [elastisys/ck8s-base-vm#24]

**Comment by geoff-elastisys** [comment]
meeting with @cristiklein , @jakubkrzywda  and @ewnetu to discuss if we should build image for k8s 1.17 or 1.18

**Comment by geoff-elastisys** [comment]
base image already exists for 1.17 - we do need an ami for 1.18 though

edit: we have an image, need to create ami on aws

**Comment by Xartos** [comment]
There's a release for 1.18 as well (https://github.com/elastisys/ck8s-base-vm/releases/tag/v1.18.10%2Bck8s0). We just need to upload it to AWS
