### ISSUE TITLE
Create base image for kubernetes V1.19

### ISSUE THREAD

**Issue by ewnetu** [elastisys/ck8s-base-vm#25]
As the name indicates the goal of this task is to build a base image for kubernetes V1.19. 
Note that: this task should be completed after kubernetes v1.20 is released since kubeadmin and kubectl are one version ahead in compliant kubernetes. See kubernetes v1.20 release info here https://www.kubernetes.dev/resources/release/

**Comment by tordsson** [comment]
Deprecated by kubespray?

**Comment by viktor-f** [comment]
> Deprecated by kubespray?

I guess this depends a bit on if we can migrate selected customer clusters to kubespray before k8s 1.18 is not supported anymore, since they want to stay on a supported k8s version. I don't think we have any other customers/clusters where this could be a problem.
